FROM golang:1.19.1 AS builder

WORKDIR /src/
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bullseye

EXPOSE 3000 4000

RUN mkdir -p /app/stdpics
COPY stdpics/profilepic.jpg /app/stdpics/profilepic.jpg
COPY stdpics/grouppic.jpg /app/stdpics/grouppic.jpg

WORKDIR /app/
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
