FROM golang:1.19.1 AS builder

ENV GOFLAGS="-buildvcs=false"

### Copy Go code
WORKDIR /src/
COPY . .

### Build executables
RUN go build -o /app/webapi ./cmd/webapi

### Create final container
FROM debian:bullseye

### Inform Docker about which port is used
EXPOSE 3000 4000

### Create a directory for the storage and copy the default propic there
RUN mkdir -p /app/storage
#COPY storage/default_profile_photo.jpg /app/storage/default_profile_photo.jpg

### Copy the build executable from the builder image
WORKDIR /app/
COPY --from=builder /app/webapi ./

### Executable command
CMD ["/app/webapi"]