
services:
  init:
    image: alpine:latest
    command: ["sh", "-c", "echo 'Alpine image pulled'"]

  node:
    image: node:18.12.0
    command: ["sh", "-c", "echo 'Node.js 18.12.0 image pulled'"]

  go:
    image: golang:1.18.0
    command: ["sh", "-c", "echo 'Golang 1.18.0 image pulled'"]

  nginx:
    image: nginx:1.21.3
    ports:
      - "8080:80"
    volumes:
      - .:/app
    command: ["sh", "-c", "echo 'Nginx 1.21.3 image pulled'"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "80:80"
    volumes:
      - .:/app
    user: root
    command: ["sh", "-c", "cd /app && ./webui"]
    environment:
      - ENV=development
    depends_on:
      - init
      - node
      - go
      - nginx

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - init
      - node
      - go
      - nginx