### create user 1

POST http://localhost:3000/session HTTP/1.1
content-type: application/json

{
    "name": "matt"
}

### create user 2

POST http://localhost:3000/session HTTP/1.1
content-type: application/json

{
    "name": "lachi"
}

### create user 3

POST http://localhost:3000/session HTTP/1.1
content-type: application/json

{
    "name": "eros"
}

### new chat

POST http://localhost:3000/users/1/conversations HTTP/1.1
content-type: application/json
Authorization: 1

{
    "name": "Calcetto",
    "members": [{ "id": 1, "name": "matt" }, {"id": 2, "name": "lachita"}]
}

### change name

PUT http://localhost:3000/users/2/name HTTP/1.1
content-type: application/json
Authorization: 2

{
    "name": "lachitha"
}

### leave group 1

DELETE http://localhost:3000/users/1/groups/1 HTTP/1.1
content-type: application/json
Authorization: 1

### leave group 2

DELETE http://localhost:3000/users/2/groups/1 HTTP/1.1
content-type: application/json

### getMyConvs

GET http://localhost:3000/users/1/conversations HTTP/1.1
Content-Type: application/json
Authorization: 1

### getConv 1

GET http://localhost:3000/users/1/conversations/1 HTTP/1.1
Content-Type: application/json
Authorization: 1

### addToGroup 3

PUT  http://localhost:3000/users/1/groups/2 HTTP/1.1
Content-Type: application/json
Authorization: 1

{
    "id": 3,
    "name": "eros"
}